export const ResetPassword = async (data: object) => {
    try {
        console.log(data)
    } catch (error) {
        console.log(error)
    }
}